### Register new user
POST /api/v1/users HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "firstname": "Gerardo",
  "lastname": "asdad",
  "dateOfBirth": "1997-04-01",
  "document": "72489544039",
  "email": "me@gerardo-junior.com",
  "password": "12xablaU@",
  "address": "R. sei la onde, 69   sdsdasd sd asdasdasd s dasdasdasd",
  "mobileNumber": "1197677274",
  "gender": "MALE1"
}

### Login
POST /api/v1/auth/login HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "email": "me@gerardo-junior.com",
  "password": "12xablaU@"
}

### Search user
GET /api/v1/users HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer <TOKEN>

{
  "fullName": "Gerardo"
}

### Get user
GET /api/v1/users/89016061002 HTTP/1.1
Host: localhost:8080
Authorization: Bearer <TOKEN>

### Update user
PUT /api/v1/users/89016061002 HTTP/1.1
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer <TOKEN>

{
  "firstname": "ze 2",
  "lastname": "da silva",
  "password": "xabl!A2",
  "address": "R. sei la onde, 69",
  "mobileNumber": "2197677274",
  "gender": "MALE"
}