version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    env_file:
      - .env.example

  mysql:
    image: mysql:latest
    env_file:
      - .env.example
