version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    env_file:
      - .env.local
    environment:
      - JAVA_OPTS_EXT=-Dspring.profiles.active="local"
    depends_on:
      - db

  db:
    image: mysql:8.0.35
    env_file:
      - .env.local
    ports:
      - 3306
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  dbdata:
