spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}?serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: DemoService

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:change_me}
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  port: 8080

bezkoder:
  openapi:
    dev-url: http://localhost:8088
    prod-url: https://localhost:8080